# Generated by Django 4.1.4 on 2023-01-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
