# Generated by Django 4.1.4 on 2023-01-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='test',
        ),
    ]
